---
# Cozy Hyprland Menu Configuration

menus:
  main:
    title: "Main Menu"
    items:
      - name: "Apps"
        icon: "󰀻"
        action: "drun"
        description: "Launch applications"

      - name: "Capture"
        icon: "󰄀"
        action: "submenu"
        submenu:
          title: "Capture"
          items:
            - name: "Screenshot"
              icon: "󰹑"
              action: "submenu"
              submenu:
                title: "Screenshot"
                items:
                  - name: "Region"
                    icon: "󰆞"
                    action: "command"
                    command: "grim -g \"$(slurp)\" - | wl-copy"
                  - name: "Window"
                    icon: "󰖯"
                    action: "command"
                    command: "grim -o \"$(hyprctl -t monitors | grep -o 'Monitor [^:]*' | head -1 | cut -d' ' -f2)\" - | wl-copy"
                  - name: "Display"
                    icon: "🖥️"
                    action: "command"
                    command: "grim -o \"$(hyprctl -t monitors | grep -o 'Monitor [^:]*' | head -1 | cut -d' ' -f2)\" - | wl-copy"
            - name: "Screenrecord"
              icon: "󰎁"
              action: "submenu"
              submenu:
                title: "Screenrecord"
                items:
                  - name: "Region"
                    icon: "󰆞"
                    action: "notify"
                    message: "Region recording not implemented - customize this function"
                  - name: "Display"
                    icon: "🖥️"
                    action: "notify"
                    message: "Display recording not implemented - customize this function"
            - name: "Color"
              icon: "🎨"
              action: "command"
              command: "pkill hyprpicker || hyprpicker -a"

      - name: "Toggle"
        icon: "󰌢"
        action: "submenu"
        submenu:
          title: "Toggle"
          items:
            - name: "Nightlight"
              icon: "🌙"
              action: "script"
              script: "~/.config/hypr/bin/hyprland-toggle-nightlight"
            - name: "Idle Lock"
              icon: "🔒"
              action: "script"
              script: "~/.config/hypr/bin/hyprland-toggle-idle"
            - name: "Top Bar"
              icon: "📊"
              action: "script"
              script: "~/.config/hypr/bin/hyprland-toggle-waybar"
            - name: "Do Not Disturb"
              icon: "🔕"
              action: "script"
              script: "~/.config/hypr/bin/hyprland-toggle-dnd"
            - name: "Airplane Mode"
              icon: "✈️"
              action: "script"
              script: "~/.config/hypr/bin/hyprland-toggle-airplane-mode"

      - name: "Setup"
        icon: "⚙️"
        action: "submenu"
        submenu:
          title: "Setup"
          items:
            - name: "Audio"
              icon: "🔊"
              action: "command"
              command: "pavucontrol &"
            - name: "Network Manager"
              icon: "󰤨"
              action: "command"
              command: "kitty --class TUI.float nmtui"
            - name: "Bluetooth"
              icon: "📱"
              action: "notify"
              message: "Not implemented - customize this function"
            - name: "Power Profile"
              icon: "🔋"
              action: "submenu"
              submenu:
                title: "Power Profile"
                dynamic: true
                command: "powerprofilesctl list | grep -E '^\\*?[[:space:]]*[a-zA-Z-]+' | sed 's/^\\*[[:space:]]*//'"
                current_command: "powerprofilesctl get"
                set_command: "powerprofilesctl set"
            - name: "Monitors"
              icon: "🖥️"
              action: "edit"
              file: "~/.config/hypr/monitors.conf"
            - name: "Keyboard"
              icon: "⌨️"
              action: "notify"
              message: "Not implemented - customize this function"
            - name: "Mouse"
              icon: "🖱️"
              action: "notify"
              message: "Not implemented - customize this function"
            - name: "Privacy"
              icon: "🔒"
              action: "notify"
              message: "Not implemented - customize this function"
            - name: "Users"
              icon: "👥"
              action: "notify"
              message: "Not implemented - customize this function"
            - name: "Region"
              icon: "🌍"
              action: "notify"
              message: "Not implemented - customize this function"
            - name: "Date & Time"
              icon: "🕐"
              action: "notify"
              message: "Not implemented - customize this function"
            - name: "Keybindings"
              icon: "⌨️"
              action: "edit"
              file: "~/.config/hypr/bindings.conf"
              condition: "file_exists"
              condition_file: "~/.config/hypr/bindings.conf"
            - name: "Input"
              icon: "⌨️"
              action: "edit"
              file: "~/.config/hypr/input.conf"
              condition: "file_exists"
              condition_file: "~/.config/hypr/input.conf"
            - name: "DNS"
              icon: "🌐"
              action: "notify"
              message: "Not implemented - customize this function"
            - name: "Config"
              icon: "⚙️"
              action: "submenu"
              submenu:
                title: "Config"
                items:
                  - name: "Hyprland"
                    icon: "󰖳"
                    action: "submenu"
                    submenu:
                      title: "Hyprland Config"
                      items:
                        - name: "Main Config"
                          icon: "📄"
                          action: "edit"
                          file: "~/.config/hypr/hyprland.conf"
                        - name: "Input"
                          icon: "⌨️"
                          action: "edit"
                          file: "~/.config/hypr/input.conf"
                          condition: "file_exists"
                          condition_file: "~/.config/hypr/input.conf"
                        - name: "Bindings"
                          icon: "🔗"
                          action: "edit"
                          file: "~/.config/hypr/bindings.conf"
                          condition: "file_exists"
                          condition_file: "~/.config/hypr/bindings.conf"
                        - name: "Monitors"
                          icon: "🖥️"
                          action: "edit"
                          file: "~/.config/hypr/monitors.conf"
                        - name: "Advanced"
                          icon: "🔧"
                          action: "submenu"
                          submenu:
                            title: "Hyprland Advanced"
                            items:
                              - name: "Hypridle"
                                icon: "⏰"
                                action: "edit_restart"
                                file: "~/.config/hypr/hypridle.conf"
                                restart_command: "pkill hypridle && hypridle &"
                              - name: "Hyprlock"
                                icon: "🔒"
                                action: "edit"
                                file: "~/.config/hypr/hyprlock.conf"
                              - name: "Hyprsunset"
                                icon: "🌅"
                                action: "edit_restart"
                                file: "~/.config/hypr/hyprsunset.conf"
                                restart_command: "pkill hyprsunset && hyprsunset &"
                  - name: "Applications"
                    icon: "📱"
                    action: "submenu"
                    submenu:
                      title: "Application Config"
                      items:
                        - name: "Waybar"
                          icon: "📊"
                          action: "edit_restart"
                          file: "~/.config/waybar/config.jsonc"
                          restart_command: "pkill waybar && waybar &"
                        - name: "Swayosd"
                          icon: "🔊"
                          action: "edit_restart"
                          file: "~/.config/swayosd/config.toml"
                          restart_command: "pkill swayosd && swayosd &"
                        - name: "Mako"
                          icon: "🔔"
                          action: "edit_restart"
                          file: "~/.config/mako/config"
                          restart_command: "pkill mako && mako &"
                        - name: "Wofi"
                          icon: "🔍"
                          action: "submenu"
                          submenu:
                            title: "Wofi Config"
                            items:
                              - name: "Style"
                                icon: "🎨"
                                action: "edit"
                                file: "~/.config/wofi/style.css"
                              - name: "Config"
                                icon: "⚙️"
                                action: "edit"
                                file: "~/.config/wofi/config"
                              - name: "Menu Script"
                                icon: "📜"
                                action: "edit"
                                file: "~/.config/hypr/bin/hyprland-menu"
                  - name: "System"
                    icon: "⚙️"
                    action: "submenu"
                    submenu:
                      title: "System Config"
                      items:
                        - name: "SDDM"
                          icon: "🖥️"
                          action: "submenu"
                          submenu:
                            title: "SDDM Config"
                            items:
                              - name: "Main Config"
                                icon: "📄"
                                action: "edit"
                                file: "~/.config/sddm/sddm.conf"
                              - name: "Theme"
                                icon: "🎨"
                                action: "submenu"
                                submenu:
                                  title: "SDDM Theme"
                                  items:
                                    - name: "Theme Config"
                                      icon: "⚙️"
                                      action: "edit"
                                      file: "~/.config/sddm/themes/cozy/configs/dark.conf"
                                    - name: "Components"
                                      icon: "🧩"
                                      action: "submenu"
                                      submenu:
                                        title: "SDDM Components"
                                        items:
                                          - name: "Login Screen"
                                            icon: "🔐"
                                            action: "edit"
                                            file: "~/.config/sddm/themes/cozy/components/LoginScreen.qml"
                                          - name: "User Selector"
                                            icon: "👤"
                                            action: "edit"
                                            file: "~/.config/sddm/themes/cozy/components/UserSelector.qml"
                                          - name: "Session Selector"
                                            icon: "🖥️"
                                            action: "edit"
                                            file: "~/.config/sddm/themes/cozy/components/SessionSelector.qml"
                        - name: "Environment"
                          icon: "🌍"
                          action: "edit"
                          file: "~/.config/hypr/envs.conf"

      - name: "System"
        icon: "󰍛"
        action: "submenu"
        submenu:
          title: "System"
          items:
            - name: "Lock"
              icon: "🔒"
              action: "command"
              command: "hyprlock"
            - name: "Suspend"
              icon: "😴"
              action: "command"
              command: "systemctl suspend"
            - name: "Relaunch"
              icon: "🔄"
              action: "notify"
              message: "Relaunch not implemented - customize this function"
            - name: "Restart"
              icon: "🔄"
              action: "command"
              command: "systemctl reboot"
            - name: "Shutdown"
              icon: "⏻"
              action: "command"
              command: "systemctl poweroff"

# Configuration for the menu system
config:
  # Default menu to show when no argument is provided
  default_menu: "main"

  # Menu application to use (wofi, rofi, etc.)
  menu_app: "wofi"

  # Menu application arguments
  menu_args:
    - "--insensitive"

  # Terminal application
  terminal: "kitty"

  # Editor application
  editor: "nvim"

  # Notification command
  notify_command: "notify-send"
